version: '3.9'

services:
  db:
    image: postgres:15
    container_name: tracktraineat-db-dev
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
     context: ./backend
    container_name: tracktraineat-backend
    env_file:
    - .env.docker
    ports:
    - "8000:8000"
    depends_on:
    - db
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    volumes:
    - ./backend:/app


  frontend:
    build:
      context: ./frontend
    container_name: tracktraineat-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
