site_name: Track Train Eat
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
docs_dir: docs
nav:
  - Home: index.md
  - Arc42: arc42.md
  - Install: install.md
  - C4-Modell: C4.md
  - SQS:
      - Techstack: SQS/Techstack.md
      - C4: SQS/C4.md
      - Test-Strategie: SQS/test.md
      - Ausfallsicherheit: SQS/Ausfallsicherheit.md
  - ADRs:
      - Datenbank: adr/database-adr.md
      - Techstack: adr/techstack-adr.md
      - Architektur: adr/architektur-adr.md
