site_name: Track Train Eat
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
docs_dir: docs
nav:
  - Arc42: arc42.md
  - Install: install.md
  - Test: test.md
