name: Build Only

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main #muss natürlich geändert werden, aber da sonarcloud nur auf main läuft hier zu testwecken gelassen.
      - feature/**
      - fix/**

jobs:
  build:
    name: Check Frontend & Backend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build Backend
        run: |
          cd backend
          npm ci
          npm run build

      - name: Install & Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
