name: E2E Tests (Playwright)

on:
  push:
    paths:
      - 'frontend/src/tests/e2e/**'
      - '.github/workflows/e2e.yml'
  workflow_dispatch:

jobs:
  e2e:
    name: Playwright E2E
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgresUser
          POSTGRES_PASSWORD: defaultPassword
          POSTGRES_DB: tracktraineat_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd backend && npm ci
          cd ../frontend && npm ci

      - name: Set Up Env Files
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > backend/.env.test
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env.test
          echo "SPOONACULAR_API_KEY=${{ secrets.SPOONACULAR_API_KEY }}" >> backend/.env.test

          echo "VITE_API_URL=http://localhost:8000" > frontend/.env
          echo "SPOONACULAR_API_KEY=${{ secrets.SPOONACULAR_API_KEY }}" >> frontend/.env

      - name: Setup Database
        run: |
          cd backend
          npx prisma generate
          npx prisma migrate deploy --schema=prisma/schema.prisma

      - name: Start Backend and Frontend
        run: |
          nohup npm run dev --prefix backend > backend.log 2>&1 &
          nohup npm run dev --prefix frontend > frontend.log 2>&1 &
          sleep 10

      - name: Run Playwright Tests
        run: |
          cd frontend
          npx playwright install --with-deps
          npx playwright test src/tests/e2e
